export default function Terms() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-12 space-y-6 text-[#333]">
      <h1 className="text-2xl font-bold text-[#1a3a2a]">Terms of Service</h1>
      <p className="text-sm text-[#555]">Effective: April 2026</p>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">1. Acceptance</h2>
        <p>
          By signing in to Ghars you agree to these Terms. If you do not agree,
          do not use the service. We may update these Terms; continued use
          constitutes acceptance.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">2. Description of service</h2>
        <p>
          Ghars is a daily Islamic reflection app pairing Quranic verses with
          AI-generated missions, tracking your spiritual growth through a garden
          metaphor. Authentication is provided by the Quran Foundation — you
          must hold a valid Quran Foundation account.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">3. User content</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>You retain ownership of the reflections you write.</li>
          <li>
            By submitting a reflection you grant Ghars a limited licence to
            process it with an AI model solely to evaluate depth and generate
            feedback. Text is not retained by the AI provider beyond the
            immediate request.
          </li>
          <li>
            Do not submit content that is unlawful, harmful, or violates
            others&apos; rights.
          </li>
        </ul>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">4. Quranic content</h2>
        <p>
          Verses, translations, tafsir, and audio are retrieved from the Quran
          Foundation Content API and are subject to the Quran Foundation&apos;s
          own terms and licences. Ghars does not claim ownership over any
          Quranic content.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">5. AI-generated content</h2>
        <p>
          Daily missions and reflection feedback are generated by Claude
          (Anthropic). AI output may contain errors and is not a substitute for
          qualified religious guidance. Consult a knowledgeable scholar for
          matters of Islamic law or practice.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">
          6. Account &amp; data deletion
        </h2>
        <p>
          To delete your account and all data, email{" "}
          <a
            href="mailto:ahmaddzafranmohamadbustaman@gmail.com"
            className="text-[#2d6a4f] underline"
          >
            ahmaddzafranmohamadbustaman@gmail.com
          </a>{" "}
          with subject &ldquo;Delete my Ghars account&rdquo;. We will process
          within 7 days.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">
          7. Disclaimers &amp; limitation of liability
        </h2>
        <p>
          Ghars is provided &ldquo;as is&rdquo; without warranty. To the fullest
          extent permitted by law we are not liable for indirect, incidental, or
          consequential damages from use of the service.
        </p>
      </section>

      <section className="space-y-3 text-sm leading-relaxed">
        <h2 className="font-semibold text-base">8. Governing law</h2>
        <p>These Terms are governed by the laws of Malaysia.</p>
      </section>

      <section className="text-sm leading-relaxed">
        <h2 className="font-semibold text-base mb-2">Contact</h2>
        <p>
          <a
            href="mailto:ahmaddzafranmohamadbustaman@gmail.com"
            className="text-[#2d6a4f] underline"
          >
            ahmaddzafranmohamadbustaman@gmail.com
          </a>
        </p>
      </section>
    </main>
  );
}
